FROM debian:latest
USER root
RUN apt update -y
RUN apt upgrade -y
RUN apt install nginx -y
RUN apt install curl -y
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.crt /etc/nginx/ssl/nginx.crt
COPY nginx.key /etc/nginx/ssl/nginx.key
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
