FROM debian:latest
USER root
RUN apt update -y
RUN apt upgrade -y
RUN apt install nginx -y
COPY nginx.crt /etc/nginx/ssl/nginx.crt
COPY nginx.key /etc/nginx/ssl/nginx.key
COPY index.html /var/www/html/index.html
COPY default /etc/nginx/sites-enabled/default
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
