name: app docker container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: sudo ~/actions-runner/_work/opdracht2/opdracht2/containers/docker compose up
